/**
 * Centralized Security Gateway & SOC Event Constants
 */
const SECURITY_EVENT_TYPES = Object.freeze({
  GATEWAY_BLOCKED_REQUEST: "GATEWAY_BLOCKED_REQUEST",
  ADMIN_UNBLOCK_CLIENT: "ADMIN_UNBLOCK_CLIENT",
  FAILED_LOGIN_ATTEMPT: "FAILED_LOGIN_ATTEMPT",
  BRUTE_FORCE_PATTERN: "BRUTE_FORCE_PATTERN",
  SUSPICIOUS_OTP_ATTEMPT: "SUSPICIOUS_OTP_ATTEMPT",
  SUCCESSFUL_LOGIN: "SUCCESSFUL_LOGIN",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  EMAIL_CHANGED: "EMAIL_CHANGED",
  SUSPICIOUS_TRAFFIC: "SUSPICIOUS_TRAFFIC",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  ANOMALOUS_BOT_TRAFFIC: "ANOMALOUS_BOT_TRAFFIC",
  SIMULATION_STARTED: "SIMULATION_STARTED",
  SIMULATION_STOPPED: "SIMULATION_STOPPED",
  SIMULATION_REQUEST: "SIMULATION_REQUEST",
  USER_TEMPORARILY_BLOCKED: "USER_TEMPORARILY_BLOCKED",
  USER_UNBLOCKED: "USER_UNBLOCKED",
  WEBSITE_LOCKDOWN_ENABLED: "WEBSITE_LOCKDOWN_ENABLED",
  WEBSITE_LOCKDOWN_DISABLED: "WEBSITE_LOCKDOWN_DISABLED",
});

const ROLES = Object.freeze({
  USER: "user",
  ADMIN: "admin",
  SUPER_ADMIN: "super_admin",
});

const LOCKDOWN_MODES = Object.freeze({
  ONLINE: "ONLINE",
  LOCKDOWN: "LOCKDOWN",
});

const BLOCK_SOURCES = Object.freeze({
  AI_SECURITY_GATEWAY: "AI_SECURITY_GATEWAY",
  ADMIN_MANUAL: "ADMIN_MANUAL",
  SYSTEM: "SYSTEM",
});

const SEVERITY_LEVELS = Object.freeze({
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});

const GATEWAY_DECISIONS = Object.freeze({
  NORMAL: "NORMAL",
  SUSPICIOUS: "SUSPICIOUS",
  HIGH_RISK: "HIGH_RISK",
  CRITICAL: "CRITICAL",
  BLOCKED: "BLOCKED",
});

const GATEWAY_ACTIONS = Object.freeze({
  ALLOWED: "ALLOWED",
  MONITORED: "MONITORED",
  RATE_LIMITED: "RATE_LIMITED",
  CHALLENGED: "CHALLENGED",
  BLOCKED: "BLOCKED",
  ALERTED: "ALERTED",
});

const CLIENT_TYPES = Object.freeze({
  REAL: "REAL",
  SIMULATION: "SIMULATION",
});

module.exports = {
  SECURITY_EVENT_TYPES,
  ROLES,
  LOCKDOWN_MODES,
  BLOCK_SOURCES,
  SEVERITY_LEVELS,
  GATEWAY_DECISIONS,
  GATEWAY_ACTIONS,
  CLIENT_TYPES,
};
